services:
    web:
        build: .
        container_name: "web_app"
        expose:
            - "3000"
        environment:
            - NODE_ENV=production
        env_file:
            - .env
        networks:
            - webnet
    nginx:
        image: nginx:stable-alpine
        container_name: "nginx_proxy"
        depends_on:
            - web
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
            - certbot-etc:/etc/letsencrypt
            - certbot-var:/var/lib/letsencrypt
        networks:
            - webnet
    certbot:
        image: certbot/certbot
        container_name: "certbot"
        volumes:
            - certbot-etc:/etc/letsencrypt
            - certbot-var:/var/lib/letsencrypt
        entrypoint: >
            sh -c "trap exit TERM; while :; do
            certbot renew --webroot -w /var/lib/letsencrypt;
            sleep 12h & wait $${!}; done"

volumes:
    certbot-etc:
    certbot-var:

networks:
    webnet:
