services:
    web:
        build: .
        container_name: "web_app"

        restart: always
        expose:
            - "3000"
        environment:
            - NODE_ENV=production
        env_file:
            - .env
        networks:
            - webnet
    nginx:
        image: nginx:stable-alpine
        container_name: "nginx_proxy"
        restart: always
        depends_on:
            - web
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
            - ./data/certbot/www:/var/lib/letsencrypt
            - ./data/certbot/conf:/etc/letsencrypt
        networks:
            - webnet
    certbot:
        image: certbot/certbot
        container_name: "certbot"
        volumes:
            - ./data/certbot/www:/var/lib/letsencrypt
            - ./data/certbot/conf:/etc/letsencrypt
        entrypoint: >
            sh -c "trap exit TERM;
            while :; do
              certbot renew --webroot -w /var/lib/letsencrypt;
              sleep 12h & wait $${!}; 
            done"

volumes:
    certbot-etc:
    certbot-var:

networks:
    webnet:
