-- CreateTable
CREATE TABLE `Report` (
    `id` VARCHAR(191) NOT NULL,
    `reportPeriod` ENUM('DAILY', 'WEEKLY', 'MONTHLY', 'YEARLY') NOT NULL,
    `startDate` DATETIME(3) NOT NULL,
    `endDate` DATETIME(3) NOT NULL,
    `totalIncome` DECIMAL(10, 2) NOT NULL,
    `totalOrders` INTEGER NOT NULL,
    `completedOrders` INTEGER NOT NULL DEFAULT 0,
    `canceledOrders` INTEGER NOT NULL DEFAULT 0,
    `pendingOrders` INTEGER NOT NULL DEFAULT 0,
    `transportOrders` INTEGER NOT NULL DEFAULT 0,
    `tourOrders` INTEGER NOT NULL DEFAULT 0,
    `averageRating` DECIMAL(3, 2) NULL,
    `popularDestinations` JSON NULL,
    `topVehicleTypes` JSON NULL,
    `isAutoGenerated` BOOLEAN NOT NULL DEFAULT true,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
