name: Build Capability

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: "latest"

      - name: Setup Node.js Environment
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Check for required secrets
        run: |
          missing_secrets=0
          if [ -z "${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}" ]; then
            echo "Error: Secret SUPABASE_SERVICE_ROLE_KEY is not set."
            missing_secrets=1
          fi
          if [ -z "${{ secrets.SUPABASE_URL }}" ]; then
            echo "Error: Secret SUPABASE_URL is not set."
            missing_secrets=1
          fi
          if [ $missing_secrets -eq 1 ]; then
            exit 1
          fi

      - name: Install dependencies
        run: pnpm install

      - name: Setup prisma
        run: pnpm prisma generate

      - name: Build project
        run: pnpm build
